[project]
name = "leoss"
version = "0.1.0"
description = ""
authors = [
    {name = "KenIbarra",email = "144877753+space-hiro@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tqdm (>=4.67.3,<5.0.0)",
    "pandas (>=3.0.1,<4.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pyigrf14 (>=1.0.4,<2.0.0)",
    "websockets (>=16.0,<17.0)",
]

[tool.poetry]
packages = [{include = "leoss", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
